version = 0.1

[default]
[default.build]
[default.build.parameters]
template_file = "template.yaml"
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "thingsboard-forecast-api"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
region = "ap-southeast-1"
version = 0.1

[default]
[default.build]
[default.build.parameters]
template_file = "template.yaml"
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "thingsboard-forecast-api"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
region = "ap-southeast-1"
